### ISSUE TITLE
拉取镜像时出错

### ISSUE THREAD

**Issue by robotkeys** [yilingyi/docker-mirror#1]
[root@Data docker-mirror]# docker-mirror pull nginx
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
	/data/temp/docker-mirror/main.go:143 +0xe85

**Comment by Leif160519** [comment]
> [root@Data docker-mirror]# docker-mirror pull nginx panic: runtime error: index out of range [1] with length 1
> 
> goroutine 1 [running]: main.main() /data/temp/docker-mirror/main.go:143 +0xe85

我也发现了，而且只要是镜像名称前面没有仓库名的都拉取失败，有仓库名的就没问题
```
[root@k8s-master-01:~ 13:41:48] # docker-mirror pull nginx:latest
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
        /data/temp/docker-mirror/main.go:143 +0xe85


[root@k8s-master-01:~ 13:43:04] # docker-mirror pull nginx/nginx-ingress:latest
正在从 cloudsx.top 拉取镜像 nginx/nginx-ingress:latest
正在将镜像 nginx/nginx-ingress:latest 标记为 harbor.xxx.xxx/library/nginx-ingress:latest
正在登录到 Harbor 仓库 harbor.xxx.xxx
正在推送镜像 harbor.xxxxx/library/nginx-ingress:latest
镜像成功同步！
```

**Comment by Leif160519** [comment]
我修复了这个问题#2，可以拉取测试一下@robotkeys

**Comment by yilingyi** [comment]
这两天会更新一个版本解决该问题，并支持配置多个加速仓库地址，或者不配置。

**Comment by yilingyi** [comment]
1.1.0版本已经解决该问题，并支持设置多加速仓库、空值
