### ISSUE TITLE
Small comments

### ISSUE THREAD

**Issue by saowu** [yilingyi/docker-mirror#3]
The tool for transferring files is not convenient enough. The most troublesome thing is to change the edge image. If you can directly configure the scientific Internet access and use the proxy to pull the image, you can avoid changes to the production environment.

**Comment by yilingyi** [comment]
This is a once and for all solution, and enterprise environments should consider building a private Docker Registry to avoid the possibility of pods being unable to start properly again due to proxy failures

**Comment by yilingyi** [comment]
This is a once and for all solution, and enterprise environments should consider building a private Docker Registry to avoid the possibility of pods being unable to start properly again due to proxy failures
